title: Luka Reisman - Software Developer
description: Professional CV and portfolio of Luka Reisman, a backend developer with 7+ years of experience in scalable web services, APIs, and data platforms.